apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::634758830486:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-bLI7kyoFRT5A
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - userarn: arn:aws:iam::634758830486:user/hemanchandra
      username: hemanchandra
      groups:
        - roboshop-trainee
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-30T14:52:57Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1190"
  uid: d19a0c75-78c6-47f4-b923-214aace336b4
