apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::634758830486:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-uHVHv8SroGwf
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::634758830486:user/heman
      username: heman
    groups:
      - roboshop-trainee
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-30T09:27:31Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1172"
  uid: bdeeb974-054c-49bb-b4a4-dc9c9ba57e1d
