apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::634758830486:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-bLI7kyoFRT5A
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}

  mapUsers: |
    - userarn: arn:aws:iam::634758830486:user/heman
      username: heman
      groups:
        - roboshop-admin
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system

 