apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::634758830486:role/eksctl-roboshop-addon-iamserviceaccount-defau-Role1-20PQY9flz6gc
  creationTimestamp: "2026-05-01T18:05:26Z"
  labels:
    app.kubernetes.io/managed-by: eksctl
  name: roboshop
  namespace: default
  resourceVersion: "17023"
  uid: 1254f47b-905b-4ad8-aad2-e82ddc93520c
---